function Hd = getHighPassFilter
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 27-Aug-2018 17:17:35

Fstop = 100;   % Stopband Frequency
Fpass = 108;  % Passband Frequency
Astop = 60;   % Stopband Attenuation (dB)
Apass = 1;    % Passband Ripple (dB)
Fs    = 300;  % Sampling Frequency

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);

Hd = design(h, 'kaiserwin', ...
    'MinOrder', 'any');


